name: Lava CI
on: [push]

defaults:
    run:
      shell: bash

jobs:
  linux:
    name: Test Verilator
    runs-on: ubuntu-24.04
    timeout-minutes:
        60
    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      matrix:
        include:
          - compiler: ghc-9.8.2
            compilerKind: ghc
            compilerVersion: 9.8.2
            setup-method: ghcup
            allow-failure: false
          - compiler: ghc-9.4.8
            compilerKind: ghc
            compilerVersion: 9.4.8
            setup-method: ghcup
            allow-failure: false
      fail-fast: false
    steps:
      - name: Install GHC, cabal and verilator.
        run: |
          export GHCUP_INSTALL_BASE_PREFIX=$HOME
          export PATH=$HOME/.ghcup/bin:$PATH
          mkdir -p "$HOME/.ghcup/bin"
          sudo chmod a+x "$HOME/.ghcup/bin/ghcup"
          ghcup install ghc ${{ matrix.compilerVersion }}
          ghcup set ghc ${{ matrix.compilerVersion }}
          ghcup install cabal 3.10.3.0
          cabal v2-update
          sudo apt-get update
          sudo apt-get install -y verilator
      - name: Checkout Lava GitHub source
        uses: actions/checkout@v4
        with:
          path: source
      - name: Build and test Lava
        run: |
          find . -name "*.cabal"
          cd source
          cabal v2-test
          verilator +1800-2017ext+sv verilator.vlt --binary --trace -Wall --top-module nandgate_sim nandgate.sv nandgate_sim.sv
